### ISSUE TITLE
check_if_logged_in function failing - not finding USERID in cookie

### ISSUE THREAD

**Issue by vance00** [neRok00/ancestry-image-downloader#4]
I had to comment out this line of code:
if (not any('USERID' in cookie_val for cookie_val in response.cookies.values())):

and replace with:
if (not any('Id%3D' in cookie_val for cookie_val in response.cookies.values())):

because there was no USERID in my cookie.

My account is a Registered Guest (i.e. I am not subscribed).

**Comment by shaun-wilson** [comment]
Hi, this sounds like a non-issue, as the images are only able to be viewed by people with subscriptions. So this script won't do anything for you anyway.

**Comment by neRok00** [comment]
Hi, this sounds like a non-issue, as the images are only able to be viewed by people with subscriptions. So this script won't do anything for you anyway.
